"""Dados do guia de platina de House Flipper (jogo base, PT-BR).

Guia reescrito e ampliado: 29 passos cronológicos, os 10 compradores com perfil e
receita, os 24 troféus do jogo base, as 37 casas compráveis, o contador de 50 vendas,
as notas de Perfectionist, a ordem de perks, 7 segredos, 14 imagens e 6 fontes.

Este é o ÚNICO arquivo específico do jogo — os demais módulos são genéricos.
"""

# Identificador único do guia (kebab-case): vira o id do plugin e a pasta
# de progresso em %APPDATA%/StreamerSidekick/platinas/<id>/.
GUIDE_ID = "house-flipper"

GAME_NAME = "House Flipper — Platina"
GAME_SUBTITLE = (
    "Guia PT-BR do jogo base: rota cronológica, os 10 compradores com receita, "
    "as 37 casas e os 24 troféus."
)
ACCENT = "#4F8DFF"  # azul do assistente original

HERO_IMAGE = "https://cdn.akamai.steamstatic.com/steam/apps/613100/header.jpg"

# Parágrafo de abertura.
INTRO = "Guia de platina do House Flipper (jogo base) em português. A ideia é a mesma do guia de DREDGE: se o guia mandar fazer algo, ele também diz em qual casa, com qual móvel, em que ordem e por quê. Metade da platina são os 10 compradores — e para esses o guia traz tanto o perfil que o jogo pontua quanto a receita testada."

# Números de destaque exibidos no topo.
HERO_STATS = [
    {
        "value": "24",
        "label": "troféus",
    },
    {
        "value": "10",
        "label": "compradores",
    },
    {
        "value": "37",
        "label": "casas do jogo base",
    },
    {
        "value": "50",
        "label": "vendas",
    },
    {
        "value": "~20h",
        "label": "para a platina",
    },
]

# As 10 abas do guia.
SECTIONS = [
    {
        "key": "route",
        "num": "01",
        "nav": "Passo a passo",
        "eyebrow": "Rota cronológica",
        "title": "Siga nesta ordem",
        "lead": "Cada passo diz o que fazer, onde, quando e por que naquele momento — não é só “jogue até sair”.",
        "notices": [
            {
                "tone": "info",
                "text": "Como usar: faça o passo, marque a caixa e siga. As fases podem ser recolhidas clicando no título.",
            },
            {
                "tone": "red",
                "text": "Antes de tudo: mude a moeda para EURO e desinstale as DLCs. Perfectionist e Game Over contam as ordens e as casas das expansões, e Negotiator/Millionaire comparam valores em euro. Os dois primeiros passos da rota existem para isso.",
            },
        ],
    },
    {
        "key": "buyers",
        "num": "02",
        "nav": "Compradores",
        "eyebrow": "Os 10 leilões",
        "title": "Um troféu por comprador",
        "lead": "Metade da platina são os 10 compradores. Cada card traz o PERFIL dele (o que o jogo pontua) e a RECEITA testada (casa + itens exatos).",
        "notices": [
            {
                "tone": "info",
                "text": "O leilão é relativo: os 10 compradores pontuam a mesma casa e o troféu sai para quem der o MAIOR lance. Por isso às vezes o certo é deixar a casa suja — isso derruba os outros nove mais do que o seu alvo.",
            },
        ],
    },
    {
        "key": "trophies",
        "num": "03",
        "nav": "24 Troféus",
        "eyebrow": "Platina",
        "title": "Os 24 troféus do jogo base",
        "lead": "1 platina, 7 ouro, 8 prata e 8 bronze. Requisito conferido e o atalho mais curto para cada um.",
        "notices": [
            {
                "tone": "info",
                "text": "As DLCs têm listas de troféus separadas e não contam para esta platina.",
            },
        ],
    },
    {
        "key": "houses",
        "num": "04",
        "nav": "37 Casas",
        "eyebrow": "Game Over",
        "title": "As 37 casas do jogo base",
        "lead": "Checklist do Game Over. Vender uma vez cada uma já entrega 37 das 50 vendas do Senior Estate Agent.",
        "notices": [
            {
                "tone": "info",
                "text": "O estado da casa não importa: dá para comprar e revender crua, mesmo no prejuízo. “Almost only a garden” NÃO entra — é da DLC Garden.",
            },
        ],
    },
    {
        "key": "sales",
        "num": "05",
        "nav": "50 Vendas",
        "eyebrow": "Senior Estate Agent",
        "title": "Contador de vendas",
        "lead": "Marque uma caixa por venda concluída. Os marcos 10, 20 e 50 são os três troféus de corretor.",
        "notices": [
            {
                "tone": "info",
                "text": "Depois do Game Over toda casa pode ser recomprada e revendida infinitamente. O First Office (€ 22.478) é a mais rápida de rodar.",
            },
        ],
    },
    {
        "key": "orders",
        "num": "06",
        "nav": "Ordens",
        "eyebrow": "Perfectionist",
        "title": "As ordens e os 100%",
        "lead": "O troféu que mais trava platina no House Flipper, e por quê.",
        "notices": [],
    },
    {
        "key": "perks",
        "num": "07",
        "nav": "Perks",
        "eyebrow": "Equipamento",
        "title": "Ordem de perks para não travar a rota",
        "lead": "São 54 perks em 6 árvores no jogo base — nenhum troféu exige completá-las. Estes são os que realmente importam.",
        "notices": [],
    },
    {
        "key": "secrets",
        "num": "08",
        "nav": "Segredos",
        "eyebrow": "Easter eggs",
        "title": "Segredos, referências e a sala secreta",
        "lead": "O que está escondido nas casas — incluindo dois troféus que só saem assim.",
        "notices": [],
    },
    {
        "key": "visuals",
        "num": "09",
        "nav": "Mapas / Imagens",
        "eyebrow": "Referência visual",
        "title": "Plantas e capturas",
        "lead": "As plantas das casas de troféu e telas do jogo. A fonte de cada imagem está na legenda.",
        "notices": [],
    },
    {
        "key": "sources",
        "num": "10",
        "nav": "Fontes",
        "eyebrow": "Pesquisa cruzada",
        "title": "Fontes do guia",
        "lead": "A rota foi montada cruzando estes guias; onde eles divergiam, a diferença está anotada no card do comprador.",
        "notices": [],
    },
]

# 01 — Passo a passo: 29 passos em 5 fases.
ROUTE = [
    {
        "phase": "0 — Preparação: faça antes de encostar no jogo",
        "num": "0.1",
        "title": "Mudar a moeda para EURO (€)",
        "place": "Opções do jogo",
        "when": "Antes de tudo",
        "exact": "Nas opções, troque a moeda para Euro.",
        "why": "Negotiator (50.000) e Millionaire (1.000.000) comparam valores em euro. Em outra moeda os limiares não batem com os guias e há relatos dos dois troféus não saírem.",
        "image": "",
    },
    {
        "phase": "0 — Preparação: faça antes de encostar no jogo",
        "num": "0.2",
        "title": "Desinstalar / desativar as DLCs",
        "place": "Biblioteca do jogo",
        "when": "Antes de tudo",
        "exact": "Remova Garden, HGTV, Luxury, Pets, Farm, Dine Out, Apocalypse e Cyberpunk.",
        "why": "Perfectionist exige 100% em TODAS as ordens e Game Over exige vender TODAS as casas compráveis. Com DLC instalada, as ordens e as casas das expansões entram na conta e a platina fica muito mais longa.",
        "image": "",
    },
    {
        "phase": "0 — Preparação: faça antes de encostar no jogo",
        "num": "0.3",
        "title": "Entender como o leilão escolhe o comprador",
        "place": "Laptop",
        "when": "Antes de vender",
        "exact": "Ao pôr uma casa à venda, os 10 compradores pontuam a casa segundo o gosto deles e dão um lance. O troféu só sai quando o comprador-alvo é o MAIOR lance — não basta ele aparecer na lista.",
        "why": "É o conceito que faz o resto do guia funcionar: a pontuação é RELATIVA. Às vezes deixar a casa suja é o certo, porque derruba os outros nove mais do que o seu alvo.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/ss_66b4628cedb499f8c72661125cc9c800eef17ae1.1920x1080.jpg",
    },
    {
        "phase": "0 — Preparação: faça antes de encostar no jogo",
        "num": "0.4",
        "title": "Ordem de perks recomendada",
        "place": "Árvore de perks",
        "when": "Conforme for subindo",
        "exact": "Priorize, nesta ordem: Visão Penetrante, Longo Alcance, Pintura Básica, Azulejista e Pagamento Superior. Limpeza e Pintura sobem rápido; Construção e Demolição são lentas.",
        "why": "Visão Penetrante e Longo Alcance cortam o tempo de limpeza pela metade — é o que viabiliza o Do it ASAP. Pagamento Superior acelera todo o dinheiro da run.",
        "image": "",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.1",
        "title": "First Money",
        "place": "Laptop → 1ª ordem (Sara Lewis)",
        "when": "Primeira ordem do jogo",
        "exact": "Aceite a ordem da Sara Lewis: limpe e troque o radiador. Termine em 100%.",
        "why": "É o tutorial e o primeiro troféu.",
        "image": "https://houseflipper.wiki.gg/images/First_money.jpg?d1f2ef",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.2",
        "title": "Strongman",
        "place": "Ordem “Cleaning the garage” (Caroline Smith)",
        "when": "2ª ordem da Caroline",
        "exact": "Dentro da garagem, mire no carro e segure o botão de pegar até levantá-lo.",
        "why": "É a ordem que mais aparece com carro; aproveite a mesma visita para o Car Mechanic.",
        "image": "https://houseflipper.wiki.gg/images/Strongman.jpg?da7f1d",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.3",
        "title": "Car Mechanic",
        "place": "Ordem “Cleaning the garage”",
        "when": "Mesma visita do 1.2",
        "exact": "Equipe o Martelo de Demolição e bata no carro.",
        "why": "Se perder a janela, as casas Home and car e Pink Kingdom também têm carro.",
        "image": "https://houseflipper.wiki.gg/images/Carmechanic.jpg?4761aa",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.4",
        "title": "You’re doing it wrong",
        "place": "Qualquer job com baratas",
        "when": "Assim que ver uma barata",
        "exact": "Em vez de aspirar, equipe o Martelo de Demolição e esmague a barata.",
        "why": "Baratas aparecem nas cozinhas dos jobs de limpeza — se aspirar todas sem querer, a próxima ordem suja traz mais.",
        "image": "https://houseflipper.wiki.gg/images/Youdoitwrong.jpg?ee6aa9",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.5",
        "title": "Fechar TODAS as ordens em 100%",
        "place": "Laptop → Mail Archive",
        "when": "Durante toda a fase 1",
        "exact": "Faça cada ordem até 100% antes de sair. Depois volte ao Mail Archive e confira, uma por uma, se alguma ficou abaixo de 100% — dá para voltar e terminar.",
        "why": "É o Perfectionist. 70% já paga o bônus, então é fácil sair de um job “concluído” com 85% e travar o troféu sem perceber.",
        "image": "https://houseflipper.wiki.gg/images/Perfectionist.jpg?a32600",
    },
    {
        "phase": "1 — Ordens: o troféu mais longo sai junto com o dinheiro inicial",
        "num": "1.6",
        "title": "Do it ASAP",
        "place": "Ordem “Cleaning the garage”",
        "when": "Depois de maximizar os perks de limpeza",
        "exact": "Com Visão Penetrante e Longo Alcance no máximo, refaça a ordem e termine em menos de 1 minuto.",
        "why": "O limite é 60 segundos (não 30). Sem os perks de limpeza é praticamente impossível.",
        "image": "https://houseflipper.wiki.gg/images/Doitasap.jpg?6a453c",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.1",
        "title": "Geek — Chang Choi",
        "place": "Abandoned house (€ 31.436)",
        "when": "Primeiro comprador: é a casa mais barata",
        "exact": "Espaço único e minimalista. Receita completa na aba Compradores.",
        "why": "Começar pelas casas baratas deixa você aprender o leilão sem arriscar caixa.",
        "image": "https://houseflipper.wiki.gg/images/Nerd.jpg?2330dd",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.2",
        "title": "I’m a Belieber — Gorgio Shanua",
        "place": "Burned house (€ 30.573)",
        "when": "Junto com o 2.1",
        "exact": "Limpar tudo, só quarto + banheiro, 3x Linen Closet. Ver aba Compradores.",
        "why": "Segunda casa mais barata do jogo.",
        "image": "https://houseflipper.wiki.gg/images/Imbelieber.jpg?8a12e3",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.3",
        "title": "Just Enough — Família Jantart",
        "place": "Camping Bungalow (€ 29.826)",
        "when": "Junto com o 2.1",
        "exact": "Máximo 3 cômodos, móveis antigos e muitos tapetes. Ver aba Compradores.",
        "why": "A casa mais barata das três iniciais.",
        "image": "https://houseflipper.wiki.gg/images/Justenough.jpg?767d60",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.4",
        "title": "Mystery — Jimmy Traitor",
        "place": "Home Admin-Legends (€ 64.013)",
        "when": "Depois das três baratas",
        "exact": "NÃO limpe. Só uma Coffee table Ramvik. Ver aba Compradores.",
        "why": "Faça o Mystery ANTES do Alpha Male: os dois usam a mesma casa, e o do Jimmy é o que exige a casa suja — depois você limpa para o Rafael.",
        "image": "https://houseflipper.wiki.gg/images/Mystery.jpg?82b6eb",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.5",
        "title": "Alpha Male — Rafael Erko",
        "place": "Home Admin-Legends (€ 64.013)",
        "when": "Logo após o 2.4",
        "exact": "Recompre a mesma casa, tire os móveis da cozinha e vire o Storeroom em Sauna/Man Cave.",
        "why": "Reaproveitar a casa economiza uma compra e ainda soma +1 venda no contador.",
        "image": "https://houseflipper.wiki.gg/images/Alphamale.jpg?863965",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.6",
        "title": "Worth Every Penny — Dolan Trusk",
        "place": "House that is hiding something (€ 86.136)",
        "when": "Quando tiver ~90k",
        "exact": "Venda os móveis e tire todo o lixo. Ver aba Compradores.",
        "why": "Aproveite e abra a sala secreta do porão na mesma visita.",
        "image": "https://houseflipper.wiki.gg/images/Wortheverypenny.jpg?4134ad",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.7",
        "title": "Wall Street Shark + Knock, knock",
        "place": "Huckster’s House (€ 89.704)",
        "when": "Quando tiver ~90k",
        "exact": "Bata na porta da frente com o martelo (Knock, knock) e depois monte a casa do Jack. Ver aba Compradores.",
        "why": "Dois troféus na mesma casa — não saia sem bater na porta.",
        "image": "https://houseflipper.wiki.gg/images/Wallstreetshark.jpg?b5936c",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.8",
        "title": "Family Man — Família Jonson",
        "place": "Unsatisfying effect (€ 95.466)",
        "when": "Quando tiver ~100k",
        "exact": "Encha de camas até somar seis quartos. Ver aba Compradores.",
        "why": "A casa já vem com muitos cômodos, que é exatamente o perfil deles.",
        "image": "https://houseflipper.wiki.gg/images/Familyman.jpg?bcb994",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.9",
        "title": "Artistic Soul — Veronica Liptson",
        "place": "Variable woman’s house (€ 100.364)",
        "when": "Quando tiver ~100k",
        "exact": "Tire a pia da cozinha e pendure até 7 quadros. Ver aba Compradores.",
        "why": "Quadro é o item que mais pesa para ela.",
        "image": "https://houseflipper.wiki.gg/images/Artisticsoul.jpg?fe0b45",
    },
    {
        "phase": "2 — Os 10 compradores: um leilão de cada vez",
        "num": "2.10",
        "title": "Pro-creative — Família Smoth",
        "place": "Family house (€ 184.786)",
        "when": "Por último: é a mais cara",
        "exact": "Comprar e vender sem mexer em nada. Ver aba Compradores.",
        "why": "Deixe para o fim porque exige o maior caixa — e não dá trabalho nenhum.",
        "image": "https://houseflipper.wiki.gg/images/Pro-creative.jpg?8712d8",
    },
    {
        "phase": "3 — Game Over: venda as 37 casas uma vez",
        "num": "3.1",
        "title": "Mudar o escritório de casa",
        "place": "Laptop",
        "when": "Antes de vender o First Office",
        "exact": "Compre qualquer outra casa e mude o escritório para ela.",
        "why": "Enquanto o First Office for o seu escritório, o jogo não deixa vendê-lo — e ele conta para o Game Over.",
        "image": "",
    },
    {
        "phase": "3 — Game Over: venda as 37 casas uma vez",
        "num": "3.2",
        "title": "Vender o First Office",
        "place": "First Office (€ 22.478)",
        "when": "Logo após o 3.1",
        "exact": "Venda cru, sem reformar nada.",
        "why": "O estado não importa para o Game Over.",
        "image": "",
    },
    {
        "phase": "3 — Game Over: venda as 37 casas uma vez",
        "num": "3.3",
        "title": "Vender uma vez cada uma das 37 casas",
        "place": "Aba Casas",
        "when": "O grosso do tempo restante",
        "exact": "Compre e revenda cada casa do jogo base uma vez. Pode ser no prejuízo — não precisa reformar. Use a aba Casas como checklist.",
        "why": "É o Game Over. E como cada uma conta uma venda, você termina esta fase com 37 das 50 vendas do Senior Estate Agent já feitas.",
        "image": "https://houseflipper.wiki.gg/images/Gameover.jpg?d7f79a",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.1",
        "title": "Junior Estate Agent e Estate Agent",
        "place": "Aba Vendas",
        "when": "Sai sozinho na fase 3",
        "exact": "10 e 20 vendas.",
        "why": "Já vieram durante o Game Over; só confira na aba Vendas.",
        "image": "https://houseflipper.wiki.gg/images/Juniorestateagent.jpg?60c32e",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.2",
        "title": "Senior Estate Agent — 50 vendas",
        "place": "First Office",
        "when": "Depois do Game Over",
        "exact": "Faltam 13 vendas. Compre e revenda o First Office repetidamente — é a casa mais barata (€ 22.478) e a mais rápida de rodar.",
        "why": "Depois do Game Over toda casa pode ser recomprada e revendida infinitamente.",
        "image": "https://houseflipper.wiki.gg/images/Seniorestateagent.jpg?da9ce2",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.3",
        "title": "Negotiator — ganho de 50.000 € numa negociação",
        "place": "Alone Home (€ 364.779)",
        "when": "Quando tiver caixa para uma casa cara",
        "exact": "Reforme e ponha à venda; na tela de negociação, use a Negociação de Preço no máximo até fechar com pelo menos 50.000 € de ganho NA NEGOCIAÇÃO.",
        "why": "Não é o lucro da venda: é quanto você arrancou a mais durante a negociação. Casa cara = margem maior. Confirme que a moeda está em euro.",
        "image": "https://houseflipper.wiki.gg/images/Negotiator.jpg?dc873c",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.4",
        "title": "Millionaire — 1.000.000 € ganhos",
        "place": "Qualquer lugar",
        "when": "Sai naturalmente",
        "exact": "Continue vendendo até o total ganho passar de 1 milhão.",
        "why": "É o acumulado do jogo inteiro, não o saldo atual — provavelmente sai antes de você terminar o Game Over.",
        "image": "https://houseflipper.wiki.gg/images/Millionaire.jpg?c6d7f2",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.5",
        "title": "Conferir o Perfectionist",
        "place": "Laptop → Mail Archive",
        "when": "Antes de fechar a platina",
        "exact": "Se o troféu ainda não saiu, abra o Mail Archive e procure ordens abaixo de 100%.",
        "why": "É o troféu que mais trava platina no House Flipper, justamente porque o jogo deixa você “concluir” um job com 70%.",
        "image": "https://houseflipper.wiki.gg/images/Perfectionist.jpg?a32600",
    },
    {
        "phase": "4 — Fechamento: vendas, dinheiro e os últimos easter eggs",
        "num": "4.6",
        "title": "Platina — House Flipper",
        "place": "—",
        "when": "Fim",
        "exact": "Com os 23 troféus anteriores, a platina cai sozinha.",
        "why": "Nada é perdível: qualquer troféu que faltar pode ser refeito à vontade.",
        "image": "",
    },
]

# 02 — Os 10 compradores: perfil oficial + receita testada.
BUYERS = [
    {
        "key": "chang",
        "name": "Chang Choi",
        "trophy": "Geek",
        "tier": "ouro",
        "portrait": "https://houseflipper.wiki.gg/images/Chang.jpg?985f0b",
        "trophy_icon": "",
        "profile": "Limpeza moderada • tinta em tons de VERDE • piso não exigido • 1 banheiro simples • 1 quarto • sem preferência de sala/cozinha • quer uma casa minimalista de 2 cômodos.",
        "house": "Abandoned house",
        "price": "€ 31.436",
        "steps": [
            "Compre a Abandoned house e remova todo o lixo e as baratas.",
            "Derrube as paredes permitidas entre sala/cozinha e quarto/sala — o objetivo é virar um único espaço grande e aberto.",
            "Venda toda a mobília que veio na casa.",
            "Limpe paredes, chão e teto por completo e pinte em tom de verde.",
            "Coloque só o essencial: 1x Bed Peony, 1x Desk Anna, 1x cadeira em B, 2x armário com prateleiras e 3x figuras de coelho.",
            "Ponha à venda e confirme que Chang Choi é o MAIOR lance antes de aceitar.",
        ],
        "alt": "",
        "note": "“Minimalista” aqui é literal: cada móvel a mais que não seja de quarto/estudo derruba a pontuação dele.",
    },
    {
        "key": "dolan",
        "name": "Dolan Trusk",
        "trophy": "Worth Every Penny",
        "tier": "bronze",
        "portrait": "https://houseflipper.wiki.gg/images/Dolan.jpg?847555",
        "trophy_icon": "",
        "profile": "Limpeza ALTA • tinta BRANCA • piso preferido • exatamente 1 banheiro • exatamente 1 quarto • sem quarto de criança • quer um Escritório • coisas caras no corredor e no escritório, baratas no resto.",
        "house": "House that is hiding something",
        "price": "€ 86.136",
        "steps": [
            "Compre a House that is hiding something.",
            "Venda toda a mobília.",
            "Jogue todo o lixo fora (a sujeira em si não precisa ser esfregada para o troféu, mas limpar ajuda porque ele exige limpeza alta).",
            "Aproveite e abra a sala secreta atrás do quadro de energia, no porão.",
            "Ponha à venda e confirme que Dolan Trusk é o maior lance.",
        ],
        "alt": "",
        "note": "É a mesma casa da sala secreta — resolva o easter egg na mesma visita.",
    },
    {
        "key": "gorgio",
        "name": "Gorgio Shanua",
        "trophy": "I’m a Belieber",
        "tier": "ouro",
        "portrait": "https://houseflipper.wiki.gg/images/Gorgio.jpg?4159cc",
        "trophy_icon": "",
        "profile": "Limpeza ALTA • tinta em tons de ROSA • piso preferido • 1-2 banheiros COM banheira • 1 quarto grande • NENHUMA cozinha • quer Sauna e Closet.",
        "house": "Burned house",
        "price": "€ 30.573",
        "steps": [
            "Compre a Burned house e limpe a casa inteira — fuligem, paredes, chão e teto.",
            "Remova TODA a mobília, exceto os itens de banheiro.",
            "Adicione 1x Double Bed Warmy.",
            "Adicione 3x Linen Closet (o closet é o que ele mais valoriza).",
            "Pinte em tom de rosa se quiser margem extra.",
            "Ponha à venda e confirme que Gorgio Shanua é o maior lance.",
        ],
        "alt": "Just married’s house também funciona, mas é 8x mais cara.",
        "note": "",
    },
    {
        "key": "jack",
        "name": "Jack Tarinton",
        "trophy": "Wall Street Shark",
        "tier": "ouro",
        "portrait": "https://houseflipper.wiki.gg/images/Jack.jpg?f86700",
        "trophy_icon": "",
        "profile": "Limpeza BAIXA a moderada • a tinta mais barata • piso não exigido • 2+ banheiros • 2-4 quartos • 1 sala com kitchenette • quer Sauna e coisas baratas / estilo escandinavo.",
        "house": "Huckster’s House",
        "price": "€ 89.703",
        "steps": [
            "Compre a Huckster’s House.",
            "ANTES DE MAIS NADA: bata na porta da frente com o Martelo de Demolição → troféu Knock, knock.",
            "Remova a pia da cozinha.",
            "Instale a Sink with cabinet PRYZMAT no banheiro.",
            "Instale a Mountable Toilet Farie no banheiro E no quarto principal (2 vasos).",
            "Na sala: 2x Sofa Shadow, 1x Coffee table Foro e 1x TV de parede.",
            "Ponha à venda e confirme que Jack Tarinton é o maior lance.",
        ],
        "alt": "",
        "note": "Ele gosta de barato: não gaste com acabamento caro, isso derruba a pontuação dele.",
    },
    {
        "key": "jimmy",
        "name": "Jimmy Traitor",
        "trophy": "Mystery",
        "tier": "prata",
        "portrait": "https://houseflipper.wiki.gg/images/Jimmy.jpg?cc2c12",
        "trophy_icon": "",
        "profile": "Perfil oficial: limpeza ALTA • tinta VERMELHA obrigatória • piso obrigatório • 2+ banheiros • 1 quarto com cama de casal • 1 sala grande • quer Sauna • gosta de coisas modernas e caras • TV em todos os cômodos.",
        "house": "Home Admin-Legends",
        "price": "€ 64.012",
        "steps": [
            "Compre a Home Admin-Legends.",
            "NÃO limpe nada e não mexa na mobília.",
            "Adicione apenas 1x Coffee table Ramvik na sala.",
            "Ponha à venda e confirme que Jimmy Traitor é o maior lance.",
        ],
        "alt": "",
        "note": "Parece contradizer o perfil dele — e contradiz mesmo. O leilão é RELATIVO: numa casa suja os outros nove compradores despencam mais do que ele, então ele sobe para o topo. Se preferir o caminho “pelo perfil”, aí sim limpe tudo, pinte de vermelho e ponha TV em cada cômodo — as duas rotas funcionam.",
    },
    {
        "key": "rafael",
        "name": "Rafael Erko",
        "trophy": "Alpha Male",
        "tier": "bronze",
        "portrait": "https://houseflipper.wiki.gg/images/Rafael.jpg?7929ab",
        "trophy_icon": "",
        "profile": "Limpeza média a alta • piso preferido • 2+ banheiros • 1-2 quartos • 1 sala • quer Sauna • quer um Escritório, mas prefere um Man Cave • móveis modernos.",
        "house": "Home Admin-Legends",
        "price": "€ 64.012",
        "steps": [
            "Compre a Home Admin-Legends (a mesma do Jimmy — faça uma de cada vez).",
            "Remova os móveis da cozinha.",
            "Transforme o Storeroom em Sauna ou em Man Cave — é o que mais pesa para ele.",
            "Deixe a casa em limpeza média/alta.",
            "Ponha à venda: com isso ele já começa como maior licitante.",
        ],
        "alt": "Turtle House (€ 75.439) — vários jogadores só compram e revendem na hora.",
        "note": "",
    },
    {
        "key": "jantart",
        "name": "Família Jantart",
        "trophy": "Just Enough",
        "tier": "bronze",
        "portrait": "https://houseflipper.wiki.gg/images/Jantart.jpg?1bd414",
        "trophy_icon": "",
        "profile": "Limpeza ALTA • precisa estar pintada • piso preferido • exatamente 1 banheiro • exatamente 1 quarto • 1 sala • 1 cozinha • no MÁXIMO 3 cômodos • gosta de coisas antigas • muitos tapetes.",
        "house": "Camping Bungalow",
        "price": "€ 29.825",
        "steps": [
            "Compre o Camping Bungalow e limpe a casa.",
            "Venda apenas os móveis da sala.",
            "Instale radiadores pela casa.",
            "Ponha carpete no chão.",
            "Na sala coloque: Double bed Aspelund, cômoda clássica, planta Zantedeschia, quadro Autumn lake, tapete verde liso e 2x tapetes oblongos.",
            "Ponha à venda e confirme que a Família Jantart é o maior lance.",
        ],
        "alt": "House with uninvited guests — alternativa citada em guias PT-BR antigos.",
        "note": "Casa pequena é vantagem aqui: mais de 3 cômodos derruba a pontuação deles.",
    },
    {
        "key": "jonson",
        "name": "Família Jonson",
        "trophy": "Family Man",
        "tier": "bronze",
        "portrait": "https://houseflipper.wiki.gg/images/Jonson.jpg?17f79d",
        "trophy_icon": "",
        "profile": "Limpeza moderada • cores CLARAS • piso não exigido • 2+ banheiros • 4+ quartos • 3 quartos de criança • 1 sala de família • 1-2 cozinhas • quer Sauna • móveis de madeira baratos • muitos brinquedos.",
        "house": "Unsatisfying effect",
        "price": "€ 95.466",
        "steps": [
            "Compre a Unsatisfying effect — ela já tem muitos cômodos, que é o que eles querem.",
            "Coloque um Sofa Rodon no primeiro cômodo pequeno.",
            "Coloque uma Single bed Mantis em TODOS os outros cômodos, até somar seis quartos.",
            "Se sobrar orçamento, espalhe brinquedos baratos.",
            "Ponha à venda e confirme que a Família Jonson é o maior lance.",
        ],
        "alt": "",
        "note": "O que importa é a CONTAGEM de quartos: cada cômodo com cama vira quarto.",
    },
    {
        "key": "smoth",
        "name": "Família Smoth",
        "trophy": "Pro-creative",
        "tier": "bronze",
        "portrait": "https://houseflipper.wiki.gg/images/Smoth.jpg?f27053",
        "trophy_icon": "",
        "profile": "Limpeza ALTA • precisa estar pintada • piso preferido • 2+ banheiros • 2+ quartos • 1 sala de família • 1 cozinha • muitos brinquedos.",
        "house": "Family house",
        "price": "€ 184.786",
        "steps": [
            "Compre a Family house (ou a Just married’s house).",
            "Não mexa em nada: essas casas já vêm grandes, limpas e mobiliadas, que é exatamente o perfil deles.",
            "Ponha à venda e confirme que a Família Smoth é o maior lance.",
        ],
        "alt": "Just married’s house (€ 243.613) — mesma receita.",
        "note": "É o troféu de comprador mais barato em esforço, mas o mais caro em dinheiro. Deixe para depois de ter caixa.",
    },
    {
        "key": "veronica",
        "name": "Veronica Liptson",
        "trophy": "Artistic Soul",
        "tier": "prata",
        "portrait": "https://houseflipper.wiki.gg/images/Veronica.jpg?789be0",
        "trophy_icon": "",
        "profile": "Limpeza BAIXA a moderada • cores PASTEL • piso indiferente • exatamente 1 banheiro • exatamente 1 quarto • sem quarto de criança • 2-4 estantes de livros • MUITOS quadros • muitas plantas.",
        "house": "Variable woman’s house",
        "price": "€ 100.364",
        "steps": [
            "Compre a Variable woman’s house.",
            "Remova a pia da cozinha.",
            "Pendure até 7 quadros espalhados pela casa — é o item que mais pesa para ela.",
            "Se puder, acrescente 2 a 4 estantes e algumas plantas.",
            "Ponha à venda e confirme que Veronica Liptson é o maior lance.",
        ],
        "alt": "Alleyway of Lights — alternativa citada em guias PT-BR antigos.",
        "note": "Ela NÃO gosta de TV nem de excesso de tapete: se a casa vier com isso, tire.",
    },
]

# 03 — Os 24 troféus do jogo base.
TROPHIES = [
    {
        "id": "plat",
        "name": "House Flipper",
        "tier": "platina",
        "requirement": "Obtenha todos os outros 23 troféus do jogo base.",
        "shortcut": "Nada é perdível: toda casa pode ser recomprada e revendida quantas vezes quiser.",
        "tip": "Obtenha todos os outros 23 troféus do jogo base. — Nada é perdível: toda casa pode ser recomprada e revendida quantas vezes quiser.",
        "image": "",
    },
    {
        "id": "t02",
        "name": "Knock, knock",
        "tier": "ouro",
        "requirement": "Bata na porta da frente da Huckster’s House com o Martelo de Demolição.",
        "shortcut": "Easter egg de Breaking Bad. Faça na mesma visita em que preparar a casa do Jack Tarinton.",
        "tip": "Bata na porta da frente da Huckster’s House com o Martelo de Demolição. — Easter egg de Breaking Bad. Faça na mesma visita em que preparar a casa do Jack Tarinton.",
        "image": "https://houseflipper.wiki.gg/images/Knockknock.jpg?9403e6",
    },
    {
        "id": "t03",
        "name": "Wall Street Shark",
        "tier": "ouro",
        "requirement": "Faça Jack Tarinton vencer um leilão.",
        "shortcut": "Huckster’s House. Ver a aba Compradores para a receita exata.",
        "tip": "Faça Jack Tarinton vencer um leilão. — Huckster’s House. Ver a aba Compradores para a receita exata.",
        "image": "https://houseflipper.wiki.gg/images/Wallstreetshark.jpg?b5936c",
    },
    {
        "id": "t04",
        "name": "Geek",
        "tier": "ouro",
        "requirement": "Faça Chang Choi vencer um leilão.",
        "shortcut": "Abandoned house transformada em um único espaço minimalista. Ver aba Compradores.",
        "tip": "Faça Chang Choi vencer um leilão. — Abandoned house transformada em um único espaço minimalista. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Nerd.jpg?2330dd",
    },
    {
        "id": "t05",
        "name": "Negotiator",
        "tier": "ouro",
        "requirement": "Feche uma negociação de venda com ganho de pelo menos 50.000 €.",
        "shortcut": "Use a Negociação de Preço no talo numa casa cara (a Alone Home é a clássica). Precisa estar com a moeda em EURO.",
        "tip": "Feche uma negociação de venda com ganho de pelo menos 50.000 €. — Use a Negociação de Preço no talo numa casa cara (a Alone Home é a clássica). Precisa estar com a moeda em EURO.",
        "image": "https://houseflipper.wiki.gg/images/Negotiator.jpg?dc873c",
    },
    {
        "id": "t06",
        "name": "Do it ASAP",
        "tier": "ouro",
        "requirement": "Complete uma ordem em menos de 1 minuto.",
        "shortcut": "Refaça “Cleaning the garage” com os perks de limpeza no máximo. Não são 30 segundos: o limite é 60.",
        "tip": "Complete uma ordem em menos de 1 minuto. — Refaça “Cleaning the garage” com os perks de limpeza no máximo. Não são 30 segundos: o limite é 60.",
        "image": "https://houseflipper.wiki.gg/images/Doitasap.jpg?6a453c",
    },
    {
        "id": "t07",
        "name": "I’m a Belieber",
        "tier": "ouro",
        "requirement": "Faça Gorgio Shanua vencer um leilão.",
        "shortcut": "Burned house limpa, só quarto + banheiro. Ver aba Compradores.",
        "tip": "Faça Gorgio Shanua vencer um leilão. — Burned house limpa, só quarto + banheiro. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Imbelieber.jpg?8a12e3",
    },
    {
        "id": "t08",
        "name": "Senior Estate Agent",
        "tier": "ouro",
        "requirement": "Venda 50 casas no total.",
        "shortcut": "As 37 vendas do Game Over já contam. Faltam 13 — refaça a compra/venda da casa mais barata (First Office).",
        "tip": "Venda 50 casas no total. — As 37 vendas do Game Over já contam. Faltam 13 — refaça a compra/venda da casa mais barata (First Office).",
        "image": "https://houseflipper.wiki.gg/images/Seniorestateagent.jpg?da9ce2",
    },
    {
        "id": "t09",
        "name": "Artistic Soul",
        "tier": "prata",
        "requirement": "Faça Veronica Liptson vencer um leilão.",
        "shortcut": "Variable woman’s house com muitos quadros. Ver aba Compradores.",
        "tip": "Faça Veronica Liptson vencer um leilão. — Variable woman’s house com muitos quadros. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Artisticsoul.jpg?fe0b45",
    },
    {
        "id": "t10",
        "name": "Perfectionist",
        "tier": "prata",
        "requirement": "Complete 100% de todas as ordens.",
        "shortcut": "Nunca saia de um job com menos de 100%. Confira o Mail Archive no laptop — ordens antigas incompletas continuam contando.",
        "tip": "Complete 100% de todas as ordens. — Nunca saia de um job com menos de 100%. Confira o Mail Archive no laptop — ordens antigas incompletas continuam contando.",
        "image": "https://houseflipper.wiki.gg/images/Perfectionist.jpg?a32600",
    },
    {
        "id": "t11",
        "name": "Mystery",
        "tier": "prata",
        "requirement": "Faça Jimmy Traitor vencer um leilão.",
        "shortcut": "Home Admin-Legends SEM limpar, com uma mesinha de centro. Ver aba Compradores.",
        "tip": "Faça Jimmy Traitor vencer um leilão. — Home Admin-Legends SEM limpar, com uma mesinha de centro. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Mystery.jpg?82b6eb",
    },
    {
        "id": "t12",
        "name": "Estate Agent",
        "tier": "prata",
        "requirement": "Venda 20 casas.",
        "shortcut": "Sai sozinho no meio do Game Over.",
        "tip": "Venda 20 casas. — Sai sozinho no meio do Game Over.",
        "image": "https://houseflipper.wiki.gg/images/Estateagent.jpg?3b2d3f",
    },
    {
        "id": "t13",
        "name": "Game Over",
        "tier": "prata",
        "requirement": "Termine o jogo: venda uma vez cada casa comprável.",
        "shortcut": "São 37 casas no jogo base. O estado não importa — dá para comprar e revender crua, mesmo no prejuízo.",
        "tip": "Termine o jogo: venda uma vez cada casa comprável. — São 37 casas no jogo base. O estado não importa — dá para comprar e revender crua, mesmo no prejuízo.",
        "image": "https://houseflipper.wiki.gg/images/Gameover.jpg?d7f79a",
    },
    {
        "id": "t14",
        "name": "You’re doing it wrong",
        "tier": "prata",
        "requirement": "Mate uma barata com o Martelo de Demolição em vez do aspirador.",
        "shortcut": "Baratas aparecem nas cozinhas dos jobs de limpeza.",
        "tip": "Mate uma barata com o Martelo de Demolição em vez do aspirador. — Baratas aparecem nas cozinhas dos jobs de limpeza.",
        "image": "https://houseflipper.wiki.gg/images/Youdoitwrong.jpg?ee6aa9",
    },
    {
        "id": "t15",
        "name": "Car Mechanic",
        "tier": "prata",
        "requirement": "Bata em um carro com o Martelo de Demolição.",
        "shortcut": "Há carro no job “Cleaning the garage” e nas casas Home and car e Pink Kingdom.",
        "tip": "Bata em um carro com o Martelo de Demolição. — Há carro no job “Cleaning the garage” e nas casas Home and car e Pink Kingdom.",
        "image": "https://houseflipper.wiki.gg/images/Carmechanic.jpg?4761aa",
    },
    {
        "id": "t16",
        "name": "Millionaire",
        "tier": "prata",
        "requirement": "Ganhe seu primeiro 1.000.000 €.",
        "shortcut": "É o total ganho ao longo do jogo, não o saldo. Sai naturalmente durante o Game Over. Precisa estar com a moeda em EURO.",
        "tip": "Ganhe seu primeiro 1.000.000 €. — É o total ganho ao longo do jogo, não o saldo. Sai naturalmente durante o Game Over. Precisa estar com a moeda em EURO.",
        "image": "https://houseflipper.wiki.gg/images/Millionaire.jpg?c6d7f2",
    },
    {
        "id": "t17",
        "name": "Junior Estate Agent",
        "tier": "bronze",
        "requirement": "Venda 10 casas.",
        "shortcut": "Sai sozinho no começo do Game Over.",
        "tip": "Venda 10 casas. — Sai sozinho no começo do Game Over.",
        "image": "https://houseflipper.wiki.gg/images/Juniorestateagent.jpg?60c32e",
    },
    {
        "id": "t18",
        "name": "First Money",
        "tier": "bronze",
        "requirement": "Complete a primeira ordem (a da Sara Lewis).",
        "shortcut": "Limpeza + troca do radiador. É o tutorial.",
        "tip": "Complete a primeira ordem (a da Sara Lewis). — Limpeza + troca do radiador. É o tutorial.",
        "image": "https://houseflipper.wiki.gg/images/First_money.jpg?d1f2ef",
    },
    {
        "id": "t19",
        "name": "Family Man",
        "tier": "bronze",
        "requirement": "Faça a Família Jonson vencer um leilão.",
        "shortcut": "Unsatisfying effect cheia de quartos. Ver aba Compradores.",
        "tip": "Faça a Família Jonson vencer um leilão. — Unsatisfying effect cheia de quartos. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Familyman.jpg?bcb994",
    },
    {
        "id": "t20",
        "name": "Just Enough",
        "tier": "bronze",
        "requirement": "Faça a Família Jantart vencer um leilão.",
        "shortcut": "Camping Bungalow com tapetes e móveis antigos. Ver aba Compradores.",
        "tip": "Faça a Família Jantart vencer um leilão. — Camping Bungalow com tapetes e móveis antigos. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Justenough.jpg?767d60",
    },
    {
        "id": "t21",
        "name": "Strongman",
        "tier": "bronze",
        "requirement": "Levante um carro.",
        "shortcut": "Na 2ª ordem da Caroline Smith (“Cleaning the garage”): segure para pegar o carro.",
        "tip": "Levante um carro. — Na 2ª ordem da Caroline Smith (“Cleaning the garage”): segure para pegar o carro.",
        "image": "https://houseflipper.wiki.gg/images/Strongman.jpg?da7f1d",
    },
    {
        "id": "t22",
        "name": "Pro-creative",
        "tier": "bronze",
        "requirement": "Faça a Família Smoth vencer um leilão.",
        "shortcut": "Family house ou Just married’s house — comprar e vender sem mexer em nada.",
        "tip": "Faça a Família Smoth vencer um leilão. — Family house ou Just married’s house — comprar e vender sem mexer em nada.",
        "image": "https://houseflipper.wiki.gg/images/Pro-creative.jpg?8712d8",
    },
    {
        "id": "t23",
        "name": "Worth Every Penny",
        "tier": "bronze",
        "requirement": "Faça Dolan Trusk vencer um leilão.",
        "shortcut": "House that is hiding something sem os móveis e sem lixo. Ver aba Compradores.",
        "tip": "Faça Dolan Trusk vencer um leilão. — House that is hiding something sem os móveis e sem lixo. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Wortheverypenny.jpg?4134ad",
    },
    {
        "id": "t24",
        "name": "Alpha Male",
        "tier": "bronze",
        "requirement": "Faça Rafael Erko vencer um leilão.",
        "shortcut": "Home Admin-Legends com Sauna/Man Cave. Ver aba Compradores.",
        "tip": "Faça Rafael Erko vencer um leilão. — Home Admin-Legends com Sauna/Man Cave. Ver aba Compradores.",
        "image": "https://houseflipper.wiki.gg/images/Alphamale.jpg?863965",
    },
]

# 04 — As 37 casas compráveis do jogo base (Game Over).
HOUSES = [
    {
        "name": "First Office",
        "price": "€ 22.478",
        "size": "20,19 m²",
        "note": "Só pode ser vendida depois de mudar o escritório para outra casa. É a mais barata — use ela para farmar as vendas que faltam para 50.",
    },
    {
        "name": "Camping Bungalow",
        "price": "€ 29.826",
        "size": "32,19 m²",
        "note": "Casa do troféu Just Enough (Jantart).",
    },
    {
        "name": "Burned house",
        "price": "€ 30.573",
        "size": "36,94 m²",
        "note": "Casa do troféu I’m a Belieber (Gorgio).",
    },
    {
        "name": "Abandoned house",
        "price": "€ 31.437",
        "size": "36,94 m²",
        "note": "Casa do troféu Geek (Chang Choi).",
    },
    {
        "name": "A moving house",
        "price": "€ 43.019",
        "size": "65,75 m²",
        "note": "",
    },
    {
        "name": "House after the flood",
        "price": "€ 48.482",
        "size": "79,06 m²",
        "note": "",
    },
    {
        "name": "Connoisseur’s House",
        "price": "€ 51.103",
        "size": "78,69 m²",
        "note": "",
    },
    {
        "name": "House with uninvited guests",
        "price": "€ 51.683",
        "size": "79,94 m²",
        "note": "",
    },
    {
        "name": "Many generations house",
        "price": "€ 51.910",
        "size": "79,94 m²",
        "note": "",
    },
    {
        "name": "Suburban House",
        "price": "€ 53.565",
        "size": "73,00 m²",
        "note": "",
    },
    {
        "name": "Summer House",
        "price": "€ 59.335",
        "size": "78,94 m²",
        "note": "",
    },
    {
        "name": "Decorated House",
        "price": "€ 64.013",
        "size": "94,81 m²",
        "note": "",
    },
    {
        "name": "Home Admin-Legends",
        "price": "€ 64.013",
        "size": "94,81 m²",
        "note": "Casa de DOIS troféus: Mystery (Jimmy) e Alpha Male (Rafael). Faça um de cada vez.",
    },
    {
        "name": "House to celebrate",
        "price": "€ 65.908",
        "size": "88,88 m²",
        "note": "",
    },
    {
        "name": "Home and car",
        "price": "€ 66.187",
        "size": "105,13 m²",
        "note": "Tem carro — serve para Car Mechanic.",
    },
    {
        "name": "Room 404",
        "price": "€ 69.991",
        "size": "75,94 m²",
        "note": "Easter egg: erro HTTP 404.",
    },
    {
        "name": "A house in a thicket",
        "price": "€ 74.648",
        "size": "146,06 m²",
        "note": "",
    },
    {
        "name": "Turtle House",
        "price": "€ 75.440",
        "size": "90,69 m²",
        "note": "Alternativa para Alpha Male (Rafael).",
    },
    {
        "name": "The one to flip",
        "price": "€ 81.763",
        "size": "113,88 m²",
        "note": "",
    },
    {
        "name": "Boring house",
        "price": "€ 82.367",
        "size": "110,00 m²",
        "note": "",
    },
    {
        "name": "House that is hiding something",
        "price": "€ 86.136",
        "size": "99,69 m²",
        "note": "Casa do troféu Worth Every Penny (Dolan) e da sala secreta no porão.",
    },
    {
        "name": "Huckster’s House",
        "price": "€ 89.704",
        "size": "156,06 m²",
        "note": "Casa do troféu Wall Street Shark (Jack) e da porta do Knock, knock.",
    },
    {
        "name": "Perfect house for vacations",
        "price": "€ 92.102",
        "size": "163,38 m²",
        "note": "",
    },
    {
        "name": "The one to move in",
        "price": "€ 93.751",
        "size": "114,81 m²",
        "note": "",
    },
    {
        "name": "Unsatisfying effect",
        "price": "€ 95.466",
        "size": "169,25 m²",
        "note": "Casa do troféu Family Man (Jonson).",
    },
    {
        "name": "Variable woman’s house",
        "price": "€ 100.365",
        "size": "171,44 m²",
        "note": "Casa do troféu Artistic Soul (Veronica).",
    },
    {
        "name": "Pink Kingdom",
        "price": "€ 118.961",
        "size": "133,06 m²",
        "note": "Tem carro — serve para Car Mechanic.",
    },
    {
        "name": "Uninhabited house",
        "price": "€ 154.703",
        "size": "221,00 m²",
        "note": "",
    },
    {
        "name": "Family Residence",
        "price": "€ 163.905",
        "size": "197,75 m²",
        "note": "",
    },
    {
        "name": "Family house",
        "price": "€ 184.786",
        "size": "237,19 m²",
        "note": "Casa do troféu Pro-creative (Smoth).",
    },
    {
        "name": "Just married’s house",
        "price": "€ 243.613",
        "size": "282,16 m²",
        "note": "Alternativa para Pro-creative (Smoth) e I’m a Belieber (Gorgio).",
    },
    {
        "name": "Let it snow",
        "price": "€ 318.201",
        "size": "496,06 m²",
        "note": "",
    },
    {
        "name": "Alone Home",
        "price": "€ 364.779",
        "size": "389,31 m²",
        "note": "Réplica de Esqueceram de Mim. É a casa clássica para o Negotiator.",
    },
    {
        "name": "House on the Moon",
        "price": "€ 402.814",
        "size": "141,75 m²",
        "note": "",
    },
    {
        "name": "Castle",
        "price": "€ 447.029",
        "size": "501,25 m²",
        "note": "",
    },
    {
        "name": "House by the river",
        "price": "€ 456.743",
        "size": "488,13 m²",
        "note": "",
    },
    {
        "name": "The big house",
        "price": "€ 461.853",
        "size": "504,94 m²",
        "note": "A maior casa do jogo base.",
    },
]

# 05 — Contador de vendas.
SALES_TOTAL = 50

SALES_MILESTONES = {
    10: "Junior Estate Agent",
    20: "Estate Agent",
    50: "Senior Estate Agent",
}

# 06 — Ordens e o Perfectionist.
ORDERS_NOTES = [
    {
        "title": "A regra que trava a platina",
        "text": "O jogo paga o bônus a partir de 70% e deixa você sair do job assim. O Perfectionist exige 100% em TODAS as ordens — inclusive as antigas.",
    },
    {
        "title": "Onde conferir",
        "text": "No laptop, abra o Mail Archive: cada ordem já feita mostra a porcentagem final. Qualquer uma abaixo de 100% pode ser refeita.",
    },
    {
        "title": "O que costuma faltar para os 100%",
        "text": "Sujeira em cantos altos e atrás de móveis, manchas de parede, itens de lixo pequenos, um radiador/tomada não instalado e paredes por pintar.",
    },
    {
        "title": "Perks que ajudam",
        "text": "Visão Penetrante mostra o que ainda está sujo através dos objetos; Longo Alcance limpa de longe. Os dois juntos praticamente eliminam o “falta 3%”.",
    },
    {
        "title": "Ordens novas por e-mail",
        "text": "Algumas ordens só aparecem depois de concluir outras. Volte ao laptop com frequência: se parar de aparecer job novo, provavelmente falta terminar algum.",
    },
]

# 07 — Ordem de perks recomendada.
PERKS = [
    {
        "order": "1",
        "name": "Visão Penetrante (Cleaning)",
        "when": "O quanto antes",
        "why": "Mostra a sujeira através de móveis e paredes. É o que faz um job fechar em 100% sem caça ao tesouro — base do Perfectionist e do Do it ASAP.",
    },
    {
        "order": "2",
        "name": "Longo Alcance (Cleaning)",
        "when": "O quanto antes",
        "why": "Aumenta o alcance da limpeza: você limpa cômodos inteiros sem andar. Junto com a Visão Penetrante, viabiliza o Do it ASAP.",
    },
    {
        "order": "3",
        "name": "Pintura Básica (Painting)",
        "when": "Cedo",
        "why": "Pintura sobe rápido e várias receitas de comprador pedem cor específica (verde para o Chang, rosa para o Gorgio, pastel para a Veronica).",
    },
    {
        "order": "4",
        "name": "Azulejista (Tiling)",
        "when": "Cedo",
        "why": "Piso é “preferido” por 6 dos 10 compradores. Barato de subir e melhora a pontuação de quase todo leilão.",
    },
    {
        "order": "5",
        "name": "Pagamento Superior (Trading)",
        "when": "Assim que liberar",
        "why": "Aumenta o que você recebe por ordem e por venda. Acelera todo o resto da run — principalmente o Millionaire e as 50 vendas.",
    },
    {
        "order": "6",
        "name": "Negociação de Preço (Trading)",
        "when": "Antes do Negotiator",
        "why": "É o perk que aumenta o teto da negociação. Sem ele no máximo, arrancar 50.000 € numa única negociação fica difícil.",
    },
    {
        "order": "7",
        "name": "Demolição e Construção",
        "when": "Só no cleanup",
        "why": "São as árvores mais lentas do jogo e quase nada na platina depende delas — só a derrubada de paredes da casa do Chang Choi.",
    },
    {
        "order": "8",
        "name": "Resto da árvore",
        "when": "Opcional",
        "why": "São 54 perks em 6 árvores no jogo base. Nenhum troféu exige completá-las.",
    },
]

# 08 — Segredos e easter eggs.
SECRETS = [
    {
        "name": "Knock, knock (Breaking Bad)",
        "where": "Huckster’s House",
        "how": "Equipe o Martelo de Demolição e bata na PORTA DA FRENTE da casa.",
        "reward": "Troféu Knock, knock (ouro)",
        "image": "https://houseflipper.wiki.gg/images/Knockknock.jpg?9403e6",
    },
    {
        "name": "A sala secreta",
        "where": "House that is hiding something",
        "how": "No porão, atrás do quadro de energia, há uma parede falsa com uma sala escondida cheia de itens.",
        "reward": "Itens raros para vender — ajuda no Millionaire",
        "image": "https://houseflipper.wiki.gg/images/House_that_is_hiding_something_-_Blueprints_-_Basement.jpg?7653bf",
    },
    {
        "name": "Alone Home (Esqueceram de Mim)",
        "where": "Alone Home",
        "how": "A casa é uma réplica da casa do filme. É a maior margem de negociação do jogo.",
        "reward": "É a casa recomendada para o Negotiator",
        "image": "https://houseflipper.wiki.gg/images/Alone_Home_-_Blueprints_-_Floor_1.jpg?c60f03",
    },
    {
        "name": "Room 404",
        "where": "Room 404",
        "how": "O nome é a piada do erro HTTP 404 — “página não encontrada”.",
        "reward": "Só referência, sem troféu",
        "image": "",
    },
    {
        "name": "Psychomanteum",
        "where": "Qualquer casa",
        "how": "Monte um cômodo com menos de 5 m² contendo um assento e um espelho.",
        "reward": "Cômodo especial reconhecido pelo jogo",
        "image": "",
    },
    {
        "name": "Baratas",
        "where": "Cozinhas dos jobs de limpeza",
        "how": "Mate uma com o Martelo de Demolição em vez do aspirador.",
        "reward": "Troféu You’re doing it wrong (prata)",
        "image": "https://houseflipper.wiki.gg/images/Roaches.jpg?9ec726",
    },
    {
        "name": "Dolan Trusk e Gorgio Shanua",
        "where": "Lista de compradores",
        "how": "Os dois nomes são paródias de celebridades reais.",
        "reward": "Só referência, sem troféu",
        "image": "",
    },
]

# 09 — Plantas e capturas.
VISUALS = [
    {
        "title": "A casa do Chang Choi e a do Gorgio",
        "caption": "Plantas da Abandoned house e da Burned house — as duas casas mais baratas de troféu.",
        "image": "https://houseflipper.wiki.gg/images/Abandoned_House_and_Burned_house_Blueprint.jpg?ab085a",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Camping Bungalow — planta",
        "caption": "Máximo 3 cômodos: é o que a Família Jantart quer.",
        "image": "https://houseflipper.wiki.gg/images/Camping_bungalow_-_Blueprints_-_Floor_1.jpg?7ad99a",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Home Admin-Legends — planta",
        "caption": "A casa de dois troféus: Mystery (Jimmy) e Alpha Male (Rafael). O Storeroom vira a Sauna/Man Cave.",
        "image": "https://houseflipper.wiki.gg/images/Home_Admin-Legends_-_Blueprints_-_Floor_1.jpg?83ded2",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "House that is hiding something — porão",
        "caption": "A sala secreta fica atrás do quadro de energia.",
        "image": "https://houseflipper.wiki.gg/images/House_that_is_hiding_something_-_Blueprints_-_Basement.jpg?7653bf",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Huckster’s House — planta",
        "caption": "Casa do Wall Street Shark. A porta da frente é a do Knock, knock.",
        "image": "https://houseflipper.wiki.gg/images/Huckster%27s_House_-_Blueprints_-_Floor_1.jpg?9c5c81",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Variable woman’s house — planta",
        "caption": "Casa da Veronica Liptson: 1 quarto, 1 banheiro e muitos quadros.",
        "image": "https://houseflipper.wiki.gg/images/Variable_woman%27s_house_-_Blueprints_-_Floor_1.jpg?333bba",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Unsatisfying effect — planta",
        "caption": "Muitos cômodos: cada um vira quarto com uma cama, para a Família Jonson.",
        "image": "https://houseflipper.wiki.gg/images/Unsatisfying_effect_-_Blueprints_-_Floor_1.jpg?1adba4",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Family house — planta",
        "caption": "Casa da Família Smoth: compre e revenda sem mexer em nada.",
        "image": "https://houseflipper.wiki.gg/images/Family_house_-_Blueprints_-_Floor_1.jpg?f921a8",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "Alone Home — planta",
        "caption": "A casa mais cara e de maior margem: é onde se faz o Negotiator.",
        "image": "https://houseflipper.wiki.gg/images/Alone_Home_-_Blueprints_-_Floor_1.jpg?c60f03",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "First Office — planta",
        "caption": "20 m², a mais barata do jogo. É a casa de farmar as 13 vendas finais.",
        "image": "https://houseflipper.wiki.gg/images/First_office_-_Blueprints_-_Floor_1.jpg?65bcd5",
        "source": "House Flipper Wiki (wiki.gg)",
    },
    {
        "title": "O leilão",
        "caption": "Os compradores dão lance conforme o gosto deles. O troféu sai com o MAIOR lance.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/ss_66b4628cedb499f8c72661125cc9c800eef17ae1.1920x1080.jpg",
        "source": "Steam / Frozen District",
    },
    {
        "title": "Limpeza",
        "caption": "Visão Penetrante + Longo Alcance é o que fecha um job em 100% e libera o Do it ASAP.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/ss_3f556347267bfb571fbdba2eca76a83888570682.1920x1080.jpg",
        "source": "Steam / Frozen District",
    },
    {
        "title": "Reforma",
        "caption": "Pintura e piso pesam na pontuação de quase todo comprador.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/ss_47c2f0a7765e97ff531acac0be7481eaf0084d8f.1920x1080.jpg",
        "source": "Steam / Frozen District",
    },
    {
        "title": "Mobília",
        "caption": "Cada móvel colocado muda a pontuação: móvel a mais pode derrubar o comprador-alvo.",
        "image": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/613100/ss_d60e717912e65c85243393552c96b96efe949d96.1920x1080.jpg",
        "source": "Steam / Frozen District",
    },
]

# 10 — Fontes consultadas.
SOURCES = [
    {
        "title": "Knoef Trophy Guides — House Flipper (PS4)",
        "url": "https://knoef.info/trophy-guides/ps4-guides/house-flipper-trophy-guide/",
        "note": "Lista dos 24 troféus com tier e requisito, e a tabela de preferências dos compradores.",
    },
    {
        "title": "Trophy Tom — House Flipper Trophy Guide",
        "url": "https://www.trophy-tom.com/house-flipper-trophy-guide/",
        "note": "Receita casa a casa dos 10 troféus de comprador, com preços e itens exatos.",
    },
    {
        "title": "House Flipper Wiki (wiki.gg) — Buyers",
        "url": "https://houseflipper.wiki.gg/wiki/Buyers",
        "note": "Tabela de preferências por comprador: limpeza, cor, piso, cômodos e exigências especiais.",
    },
    {
        "title": "House Flipper Wiki (wiki.gg) — Houses",
        "url": "https://houseflipper.wiki.gg/wiki/Houses",
        "note": "Lista completa das casas com preço e metragem, e as plantas usadas neste guia.",
    },
    {
        "title": "PSNProfiles — House Flipper",
        "url": "https://psnprofiles.com/trophies/10384-house-flipper",
        "note": "Conferência da divisão oficial: 1 platina, 7 ouro, 8 prata, 8 bronze.",
    },
    {
        "title": "MetaGame.guide — House Flipper (PS4)",
        "url": "https://metagame.guide/house-flipper-ps4/trophy-guide",
        "note": "Confirmação dos limiares do Negotiator (50.000 €) e do Do it ASAP (1 minuto).",
    },
]

# Rodapé do guia.
FOOTER = "House Flipper — Platina PT-BR • guia não oficial • progresso salvo em %APPDATA%/StreamerSidekick/platinas/house-flipper/"

